# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
author_email: ii@entap.co.jp
author_name: ii masamitsu
has_binder: true
has_settings: false
kind: frontend
labextension_name: lc_index
project_short_description: Open README on started
python_name: lc_index
repository: https://github.com/entap/jupyterlab_lc_index.git
test: false

