# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: v4.1.0
_src_path: https://github.com/jupyterlab/extension-template
has_binder: true
has_settings: false
kind: frontend
labextension_name: lc_index
project_short_description: Open README on started
python_name: lc_index
repository: https://github.com/NII-cloud-operation/Jupyter-LC_index.git
test: false

